package:
  name: kyle_hello
  version: 1.0

source:
  path: .

requirements:
  build:
    - cmake
    - make
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - scikit-build-core
    - pybind11
  run:
    - python

build:
  script:
    - {{ PYTHON }} -m pip install .

test:
  commands:
    - python -m pytest
  requires:
    - pytest
  source_files:
    - pyproject.toml
    - test.py
